apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlantis-data
spec:
  volumeName: atlantis-data
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
