apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-data
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/netology
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
